apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: bombastic-indexer
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: bombastic-indexer
    app.kubernetes.io/part-of: trustification
  name: bombastic-indexer
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: bombastic-indexer
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: bombastic-indexer
    spec:
      containers:
      - env:
        - name: REGION
          value: eu-west-1
        - name: INFRASTRUCTURE_ENABLED
          value: "true"
        - name: RUST_LOG
          value: info
        image: quay.io/redhat-user-workloads/ulilleen-tenant/trustification/bombastic-indexer@sha256:a4337e68aaa6483f335404ef274f0318e22003cfc49fa9a4af19ede4db0bf6bb
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 9010
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
